{% set name = "cuda-nvvp" %}
{% set version = "12.0.90" %}
{% set cuda_version = "12.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvvp/{{ platform }}/cuda_nvvp-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 3139235d52d0a41c56cb5caead9481154895754205b7ded7f96137fae3a9e9b1  # [linux64]
  sha256: 48928f3b3103c2fe47e557b4bd9966049b637c563af7a171358700cecf84d609  # [ppc64le]
  sha256: edc4302461ba6f9b716e146d6bb5f10f7dc776ae1268bfd383cfd74ee94fdf19  # [win]

build:
  number: 0
  skip: true  # [osx or aarch64]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm
    - cuda-nvprof

test:
  commands:
    - test -f $PREFIX/bin/nvvp      # [linux]
    - test -f $PREFIX/libnvvp/nvvp  # [linux]
    - if not exist %LIBRARY_BIN%\nvvp.bat exit 1     # [win]
    - if not exist %PREFIX%\libnvvp\nvvp.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/nvidia-visual-profiler
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVIDIA Visual Profiler to visualize and optimize the performance of your application.
  description: |
    NVIDIA Visual Profiler to visualize and optimize the performance of your
    application.
  doc_url: https://docs.nvidia.com/cuda/profiler-users-guide/index.html

extra:
  recipe-maintainers:
    - adibbley
