{% set name = "cuda-nvvp" %}
{% set version = "12.4.99" %}
{% set cuda_version = "12.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvvp/{{ platform }}/cuda_nvvp-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 607ab00d63d8b431fa5a916b64330bb5a37f211c5f950a5ff00dce17cffea403  # [linux64]
  sha256: 0561527b9a4a62078d4a0c8ee5f114d401ef6d37d72705ed248248a2c3eb48b0  # [ppc64le]
  sha256: 85850af1bbc558ea58d79a34fca982c30e7c57bed07e4a2b9323e1e9c02539d3  # [win]

build:
  number: 0
  skip: true  # [osx or aarch64]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm
    - cuda-nvprof

test:
  commands:
    - test -f $PREFIX/bin/nvvp      # [linux]
    - test -f $PREFIX/libnvvp/nvvp  # [linux]
    - if not exist %LIBRARY_BIN%\nvvp.bat exit 1     # [win]
    - if not exist %PREFIX%\libnvvp\nvvp.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/nvidia-visual-profiler
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVIDIA Visual Profiler to visualize and optimize the performance of your application.
  description: |
    NVIDIA Visual Profiler to visualize and optimize the performance of your
    application.
  doc_url: https://docs.nvidia.com/cuda/profiler-users-guide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
