{% set name = "cuda-nvvp" %}
{% set version = "12.2.142" %}
{% set cuda_version = "12.2" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvvp/{{ platform }}/cuda_nvvp-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: a5afc346567aa1a0129b901c2ea2246e69c49b21451e93cafd15c2c7cc3776e2  # [linux64]
  sha256: 7a2d6cc4ca2b9c907f68cb82ee861283d746e6a99f9fc1f7090ae4bfeafa3bbf  # [ppc64le]
  sha256: 0be4646875789d14013c70040e9e61abb4ebd4892e2418a5d4238a73ade44058  # [win]

build:
  number: 0
  skip: true  # [osx or aarch64]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm
    - cuda-nvprof

test:
  commands:
    - test -f $PREFIX/bin/nvvp      # [linux]
    - test -f $PREFIX/libnvvp/nvvp  # [linux]
    - if not exist %LIBRARY_BIN%\nvvp.bat exit 1     # [win]
    - if not exist %PREFIX%\libnvvp\nvvp.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/nvidia-visual-profiler
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVIDIA Visual Profiler to visualize and optimize the performance of your application.
  description: |
    NVIDIA Visual Profiler to visualize and optimize the performance of your
    application.
  doc_url: https://docs.nvidia.com/cuda/profiler-users-guide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
